### ISSUE TITLE
black text on dark background on "about this app" dialog

### ISSUE THREAD

**Issue by zavorra** [diegoberaldin/RaccoonForLemmy#1113] opened 2024-07-11 07:14 UTC
**Describe the bug**
Text on the about this app dialog is unreadable on dark themes

**To Reproduce**
1. Set "UI theme" to "dark"
2. Click on 'about this app'

**Expected behavior**
Text should on dark background should be light 

**Screenshots**

![Screenshot_2024-07-11-09-10-10-60_aebf63743df9a850a546c1c82dfbb3e8](https://github.com/diegoberaldin/RaccoonForLemmy/assets/12064434/4023ffa4-1aba-4c6e-8e7a-91ab6aa680c0)

**Smartphone
 
    Device: one plus 9 pro
    OS: Android 14
    Version: 1.12.0-20240620-pre (109)

**Comment by diegoberaldin** [comment] 2024-07-11 11:32
Thanks for the report, this is a duplicate of #1104.

**Closed by diegoberaldin** 2024-07-11 11:32 UTC
Labels: bug, duplicate
